version: '3.4'
services:
  web:
    build:
      context: ./
      dockerfile: .docker/nginx/Dockerfile
      target: base
    ports:
      - "${APP_PORT}:80"
    container_name: ${APP_NAME}-nginx
    volumes:
      - ./:/app
      - ./logs/nginx/:/var/log/nginx
      - ./.docker/nginx/conf/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - postgres
  php:
    #env_file:
    #  - ./.env.dev
    build:
      context: ./
      dockerfile: .docker/php-fpm/Dockerfile
      target: dev
    container_name: ${APP_NAME}-php
    ports:
      - "8080:8080"
    environment:
      PHP_IDE_CONFIG: "serverName=${APP_NAME}-php-server"
    volumes:
      - ./:/app
      - ./.docker/php-fpm/conf/php-ini-overrides.ini:/usr/local/etc/php/conf.d/php-ini-overrides.ini
      #- ./logs/symfony:/app/var/log
    depends_on:
      - postgres
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres/db:/var/lib/postgresql/data
      - ./logs/postgres/:/var/log/postgresql
    environment:
      - POSTGRES_PASSWORD=dev
      - POSTGRES_USER=dev
      - POSTGRES_DB=app_dev
      - PGDATA=/var/lib/postgresql/data/pgdata